#!/usr/bin/env node

var clog = require('c.log');
var commander = require('commander');
var request = require('request');
var xml2js = require('xml2js');

commander.version('0.0.1');

commander
  .command('yo')
  .description('Says Yo')
  .action(function () {
    clog.green('Yo!');
  });

commander
  .command('bart <station>')
  .description('Get\'s current BART departures by Station')
  .action(function (station) {
    request('http://api.bart.gov/api/etd.aspx?cmd=etd&orig=' + station + '&key=MW9S-E7SL-26DU-VV8V&dir=n', function (error, response, body) {
      if (!error && response.statusCode == 200) {
        xml2js.parseString(body, function (err, json) {
          var etd = json.root.station[0].etd;
          for(var i=0; i<etd.length; i++) {
            clog.green(etd[i].abbreviation[0] + ' in ' + etd[i].estimate[0].minutes + ' minutes');
          }
        });
      }
    });
  });

commander.parse(process.argv);
